# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPayment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'razorpay-pod', '1.2.5'
  # Pods for DemoPayment

  target 'DemoPaymentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoPaymentUITests' do
    # Pods for testing
  end

end
